// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceBricks.Cache.Postgres;

#nullable disable

namespace ServiceBricks.Cache.Postgres.Migrations
{
    [DbContext(typeof(CachePostgresContext))]
    [Migration("20240913121242_CacheV1")]
    partial class CacheV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Cache")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceBricks.Cache.EntityFrameworkCore.CacheData", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasColumnType("text");

                    b.Property<string>("CacheValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CacheKey");

                    b.HasIndex("ExpirationDate");

                    b.ToTable("CacheDatas", "Cache");
                });
#pragma warning restore 612, 618
        }
    }
}
