// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBricks.Cache.Sqlite;

#nullable disable

namespace ServiceBricks.Cache.Sqlite.Migrations
{
    [DbContext(typeof(CacheSqliteContext))]
    [Migration("20241014170151_CacheV1")]
    partial class CacheV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ServiceBricks.Cache.EntityFrameworkCore.CacheData", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheValue")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CreateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExpirationDate")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CacheKey");

                    b.HasIndex("ExpirationDate");

                    b.ToTable("CacheData");
                });
#pragma warning restore 612, 618
        }
    }
}
